USE [master]
GO
/****** Object:  Database [TaskManagementdb]    Script Date: 30.05.2022 21:42:58 ******/
CREATE DATABASE [TaskManagementdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskManagementdb', FILENAME = N'/var/opt/mssql/data/TaskManagementdb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskManagementdb_log', FILENAME = N'/var/opt/mssql/data/TaskManagementdb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TaskManagementdb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskManagementdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TaskManagementdb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TaskManagementdb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TaskManagementdb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TaskManagementdb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TaskManagementdb] SET ARITHABORT OFF 
GO
ALTER DATABASE [TaskManagementdb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TaskManagementdb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TaskManagementdb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TaskManagementdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TaskManagementdb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TaskManagementdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TaskManagementdb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TaskManagementdb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TaskManagementdb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TaskManagementdb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TaskManagementdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TaskManagementdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TaskManagementdb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TaskManagementdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TaskManagementdb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TaskManagementdb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TaskManagementdb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TaskManagementdb] SET RECOVERY FULL 
GO
ALTER DATABASE [TaskManagementdb] SET  MULTI_USER 
GO
ALTER DATABASE [TaskManagementdb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TaskManagementdb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TaskManagementdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TaskManagementdb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TaskManagementdb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TaskManagementdb', N'ON'
GO
ALTER DATABASE [TaskManagementdb] SET QUERY_STORE = OFF
GO
USE [TaskManagementdb]
GO

USE [TaskManagementdb]
GO
/****** Object:  Schema [COMMON]    Script Date: 16.06.2022 21:28:35 ******/
CREATE SCHEMA [COMMON]
GO
/****** Object:  Schema [CONTENT MANAGEMENT]    Script Date: 16.06.2022 21:28:35 ******/
CREATE SCHEMA [CONTENT MANAGEMENT]
GO
/****** Object:  Table [COMMON].[User]    Script Date: 16.06.2022 21:28:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [COMMON].[User](
	[UserId] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CONTENT MANAGEMENT].[Board]    Script Date: 16.06.2022 21:28:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONTENT MANAGEMENT].[Board](
	[BoardId] [uniqueidentifier] NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[OwnerId] [uniqueidentifier] NOT NULL,
 CONSTRAINT [PK_Board] PRIMARY KEY CLUSTERED 
(
	[BoardId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CONTENT MANAGEMENT].[Card]    Script Date: 16.06.2022 21:28:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CONTENT MANAGEMENT].[Card](
	[CardId] [uniqueidentifier] NOT NULL,
	[Title] [varchar](50) NOT NULL,
	[Description] [varchar](450) NOT NULL,
	[BoardId] [uniqueidentifier] NOT NULL,
	[Deadline] [datetime] NOT NULL,
	[CreatedAt] [datetime] NOT NULL,
 CONSTRAINT [PK_Card] PRIMARY KEY CLUSTERED 
(
	[CardId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [COMMON].[User] ([UserId], [Name], [Email], [Password]) VALUES (N'b418ea3f-4835-4a87-be14-1c99dc3b291e', N'Feyza', N'feyzaurkut1@gmail.com', N'123456')
GO
INSERT [CONTENT MANAGEMENT].[Board] ([BoardId], [Name], [OwnerId]) VALUES (N'4a79f69b-5982-402c-bc12-6efd87fd99a4', N'Feyza''s Board', N'b418ea3f-4835-4a87-be14-1c99dc3b291e')
GO
INSERT [CONTENT MANAGEMENT].[Card] ([CardId], [Title], [Description], [BoardId], [Deadline], [CreatedAt]) VALUES (N'a32d32d0-1116-4777-aa7b-086ed828930b', N'FeyzaCard1', N'asdfghjk', N'4a79f69b-5982-402c-bc12-6efd87fd99a4', CAST(N'2022-04-01T00:00:00.000' AS DateTime), CAST(N'2022-04-02T00:00:00.000' AS DateTime))
INSERT [CONTENT MANAGEMENT].[Card] ([CardId], [Title], [Description], [BoardId], [Deadline], [CreatedAt]) VALUES (N'c596a7d6-d704-4282-9d87-227e3caf8ef6', N'Deneme', N'DENEME', N'4a79f69b-5982-402c-bc12-6efd87fd99a4', CAST(N'2022-06-11T10:48:15.287' AS DateTime), CAST(N'2022-06-11T14:02:08.887' AS DateTime))
INSERT [CONTENT MANAGEMENT].[Card] ([CardId], [Title], [Description], [BoardId], [Deadline], [CreatedAt]) VALUES (N'c7ab2e7f-2f3b-4332-bc4c-937f452f5e9e', N'FeyzaCard2', N'adsfxcvb', N'4a79f69b-5982-402c-bc12-6efd87fd99a4', CAST(N'2022-05-01T00:00:00.000' AS DateTime), CAST(N'2022-05-02T00:00:00.000' AS DateTime))
INSERT [CONTENT MANAGEMENT].[Card] ([CardId], [Title], [Description], [BoardId], [Deadline], [CreatedAt]) VALUES (N'67143550-cc8f-42e1-94b8-ebdeb70505f6', N'Deneme2', N'DENEME2', N'4a79f69b-5982-402c-bc12-6efd87fd99a4', CAST(N'2022-06-11T10:48:15.287' AS DateTime), CAST(N'2022-06-11T14:08:25.357' AS DateTime))
GO
ALTER TABLE [CONTENT MANAGEMENT].[Board]  WITH CHECK ADD  CONSTRAINT [FK_Board_User] FOREIGN KEY([OwnerId])
REFERENCES [COMMON].[User] ([UserId])
GO
ALTER TABLE [CONTENT MANAGEMENT].[Board] CHECK CONSTRAINT [FK_Board_User]
GO
ALTER TABLE [CONTENT MANAGEMENT].[Card]  WITH CHECK ADD  CONSTRAINT [FK_Card_Board] FOREIGN KEY([BoardId])
REFERENCES [CONTENT MANAGEMENT].[Board] ([BoardId])
GO
ALTER TABLE [CONTENT MANAGEMENT].[Card] CHECK CONSTRAINT [FK_Card_Board]
GO
